### ISSUE TITLE
Criação da Pagina Sobre

### ISSUE THREAD

**Issue by suptec-bs** [cgonzaga/Guit-Master#3]
Vocês poderiam criar uma pagina sobre ? Agradeço.

**Comment by cgonzaga** [comment]
A pagina está  em produção

**Comment by suptec-bs** [comment]
Obrigado estou no aguardo


*Carlos Gonzaga*Diretor Tecnologia

*Perfil Prime Com. Serviços de informática Ltda.*Skype:
suporte.perfilprimerj
Tel / Fax: (21) 4042-8066 Comercial/   (21) 96406-2812
E-mail: contato@perfilprime.com.br
Site: www.p <http://www.contadoresfp.com.br/>erfilprime.com.br - Em
Construção


Em sex., 10 de jan. de 2020 às 11:31, cgonzaga <notifications@github.com>
escreveu:
